### ISSUE TITLE
Cannot install backlight without sphinx

### ISSUE THREAD

**Issue by keisuke-umezawa** [AlpacaDB/backlight#18]
```
Collecting git+https://github.com/AlpacaDB/backlight@v0.0.0 (from -r /tmp/requirements.txt (line 30))
  Cloning https://github.com/AlpacaDB/backlight (to revision v0.0.0) to /tmp/pip-req-build-01s55pch
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-01s55pch/setup.py", line 6, in <module>
        from sphinx.setup_command import BuildDoc
    ImportError: No module named 'sphinx'
```
@exilis 
This is caused by https://github.com/AlpacaDB/backlight/blob/master/setup.py .
Why do we use sphinx in setup.py?

**Comment by keisuke-umezawa** [comment]
Solved by https://github.com/AlpacaDB/backlight/pull/20.
